### ISSUE TITLE
gallery admin hiba nem lehet törölni galériát 

### ISSUE THREAD

**Issue by karrak1** [EKR-Development/FuzedCMS#15]
gallery admin hiba nem lehet törölni és mozgatni a galériában lévő képeket

**Comment by rimelek** [comment]
Kicsit konkrétabban hogy jött elő a hiba neked? Elő tudtad idézni újra a problémát, vagy csak egyszer fordult elő? Egy szerveren próbáltad, vagy esetleg több helyen is? Kipróbáltam, megy a törlés és mozgatás hibátlanul.

**Comment by karrak1** [comment]
A pontos hiba, hogy létrehozol 2 galériát, feltöltöd képpel, utána az egyiket törölni akarod, megkérdezi, hogy törlés vagy törlés és képek mozgatása ide..... nos ha ezt választod, törli a galériát, de a képeket nem mozgatja át a másik galériába (adatbázisilag)

**Comment by rimelek** [comment]
Szóval akkor a törlés hiba a galéria törlésére vonatkozik. Én a képeket töröltem eddig. Délután megnézem majd galéria törléssel.
