### ISSUE TITLE
Adminba a felhasználókat nem lehet kijelölni

### ISSUE THREAD

**Issue by karrak1** [EKR-Development/FuzedCMS#5]
Adminba a felhasználók kezelésénél nem lehet 1 felhasználót kijelölni, nincs radio gomb

**Comment by rimelek** [comment]
Nem rádió van, hanem checkbox. De nálam ott van. Kissé össze van nyomva a táblázat. Nem lehet, hogy ott van a checkbox, csak nem látszik? Belenéztél a html forrásba böngészőből?

**Comment by karrak1** [comment]
ööööö.. Igen laptopon semmi nem látszik belőle, és a mellette lévő Szerkeszt - Törlés - Megnéz ből is csak a Megnéz.

**Comment by karrak1** [comment]
Én voltam az a bizonyos, nem figyeltem, hogy admint nem lehet kijelölni, és csak megnézni lehet :(
