### ISSUE TITLE
Blog hibás id jelzés

### ISSUE THREAD

**Issue by karrak1** [EKR-Development/FuzedCMS#8]
Hibás id lekérdezéskor hibát generál nem kilép..

**Comment by rimelek** [comment]
Mi a hiba, amit generál? Azt is érdemes itt feltüntetni. Illetve mi a "hibás id lekérdezés"? Hogy lehet előidézni a hibát? Átírom a blog id-jét az url-ben egy nem létezőre?

**Comment by karrak1** [comment]
igen. de írom amit hyper írt..

Azt vettem észre az egyik kilences oldalon, ha a blog hivatkozás például ilyen vagy hasonló: ?readmore=5A=0 akkor hibát generál. Tudom, hogy érvénytelen hivatkozás de valaki hasonlóakkal szórakozik néhányszor és ettől még nem kellene hibát generálni csak "kivédeni"

**Comment by rimelek** [comment]
Így már érthetőbb. Gondolom, akkor az a fő gond itt, hogy ez ilyenkor naplózva is lesz és teleszemeteli a naplóbejegyzéseket.

**Comment by karrak1** [comment]
Igen
