### ISSUE TITLE
Fórum sorba rendezési hiba

### ISSUE THREAD

**Issue by karrak1** [EKR-Development/FuzedCMS#9]
A rendezés végrehajtódik, de nem veszi alapértelmezettnek a rendezési szempontot, mindig legrégebbi a legelső.

**Comment by rimelek** [comment]
Úgy érted, nem marad meg, ha egyszer kiválasztottam és legközelebb megint ki kell választani?

**Comment by karrak1** [comment]
igen, ez akkor lehet érdekes, ha több öldalról van szó.
